export enum UserRole {
  ADMIN = "ADMIN",
  
  STUDENT_SERVICE_MA = "STUDENT_SERVICE_MA",
  STUDENT_SERVICE_SAR = "STUDENT_SERVICE_SAR",

  FACULTY_AR = "FACULTY_AR",
  FACULTY_MA = "FACULTY_MA",
  
  DEPARTMENT_HEAD = "DEPARTMENT_HEAD",
  STUDENT = "STUDENT",
}